


// —————————————— 
// <auto-generated> 
//	This code was auto-generated 01/03/2021 11:17:19 
//	T4 template generates viewmodel's code 
//	NOTE:T4 generated code may need additional updates/addjustments by developer in order to compile a solution.
// <auto-generated> 
// —————————————–
using System;
using System.Collections.Generic;
namespace Moonlimit.DroneAPI.Domain
{

    public class ObjectDetectionViewModel : BaseDomain
    {
	  		public int DroneId { get; set; } 
			public int MissionId { get; set; } 
			public string TagNumber { get; set; } 
			public string Token { get; set; } 
			public NetTopologySuite.Geometries.Point Location { get; set; } 
			public string ObjectType { get; set; } 
			public int ObjectId { get; set; } 
			public byte[] Image { get; set; } 
	} 
	
    public class PlannedRouteViewModel : BaseDomain
    {
	  		public int DroneId { get; set; } 
			public string WaypointsJson { get; set; } 
	} 
	
    public class StatusReportViewModel : BaseDomain
    {
	  		public int DroneId { get; set; } 
			public System.DateTime LastReportTime { get; set; } 
			public bool Armed { get; set; } 
			public bool Disabled { get; set; } 
			public bool Failsafe { get; set; } 
			public float Battery { get; set; } 
			public int DroneStateType { get; set; } 
			public int DroneActionType { get; set; } 
			public bool DroneActionComplete { get; set; } 
			public int MissionStateType { get; set; } 
			public int GpsQuality { get; set; } 
			public NetTopologySuite.Geometries.Point Location { get; set; } 
	} 
	
    public class DroneCommandsViewModel : BaseDomain
    {
	  		public int DroneId { get; set; } 
			public System.DateTime Time { get; set; } 
			public int Action { get; set; } 
	} 
	
    public class DroneOnvifSettingsViewModel : BaseDomain
    {
	  		public bool Enabled { get; set; } 
			public string UserName { get; set; } 
			public string Password { get; set; } 
			public int ServicePort { get; set; } 
	} 
	
    public class GeoPointViewModel : BaseDomain
    {
	  		public NetTopologySuite.Geometries.Point Coordinates { get; set; } 
	} 
	
    public class PatrolConfigViewModel : BaseDomain
    {
	  		public float FollowDistance { get; set; } 
			public float RelativeAltitude { get; set; } 
			public float PersonScoreThreshold { get; set; } 
			public float VehicleScoreThreshold { get; set; } 
			public float TargetLostTimeouts { get; set; } 
	} 
	     
}