

// —————————————— 
// <auto-generated> 
//	This code was auto-generated 01/03/2021 11:17:27 
//	T4 template generates viewmodel mapping profile code 
//	NOTE:T4 generated code may need additional updates/addjustments by developer in order to compile a solution.
// <auto-generated> 
// —————————————–
using System;
using System.Collections.Generic;
using System.Text;
using AutoMapper;
using Moonlimit.DroneAPI.Entity;
using Moonlimit.DroneAPI.Entity.DroneCom;

namespace Moonlimit.DroneAPI.Domain.Mapping
{
    /// <summary>
    /// 
    /// </summary>
    public partial class MappingProfile : Profile
    {
        partial void SetAddedMappingProfile()
        {
    		CreateMap<ObjectDetectionViewModel, ObjectDetection>();
			CreateMap<ObjectDetection, ObjectDetectionViewModel>();
			CreateMap<PlannedRouteViewModel, PlannedRoute>();
			CreateMap<PlannedRoute, PlannedRouteViewModel>();
			CreateMap<StatusReportViewModel, StatusReport>();
			CreateMap<StatusReport, StatusReportViewModel>();
			CreateMap<DroneCommandsViewModel, DroneCommands>();
			CreateMap<DroneCommands, DroneCommandsViewModel>();
			CreateMap<DroneOnvifSettingsViewModel, DroneOnvifSettings>();
			CreateMap<DroneOnvifSettings, DroneOnvifSettingsViewModel>();
			CreateMap<GeoAreaViewModel, GeoArea>();
			CreateMap<GeoArea, GeoAreaViewModel>();
			CreateMap<GeoPointViewModel, GeoPoint>();
			CreateMap<GeoPoint, GeoPointViewModel>();
			CreateMap<PatrolConfigViewModel, PatrolConfig>();
			CreateMap<PatrolConfig, PatrolConfigViewModel>();
		}	
	} 
}

